{% set name = "larray" %}
{% set version = "0.30" %}
{% set sha256 = "11876eadb97218b9a2110edcab4cf987f650cccfa39779e01260ad2bba9e24cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/larray-project/larray/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - numpy >=1.10
    - pandas
    - pytest-runner

test:
  imports:
    - larray

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: "Labeled N-dimensional array."

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
