{% set name = "larray" %}
{% set version = "0.21" %}
{% set sha256 = "ce42d25a1c7fea81f8c2783276adf87ecc88eb47a1365b2735099b3c0117420c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/liam2/larray/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.10
    - pandas

test:
  imports:
    - larray

about:
  home: http://github.com/liam2/larray
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: "Labeled N-dimensional array."

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
