{% set version = "0.33.1" %}

package:
  name: larray
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray/archive/{{ version }}.tar.gz
  sha256: ca8569bd38c1b97de3ea152df6b1d22d373bbef40dee7f168d6761c99c748d99

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy >=1.13
    - pandas >=0.20

test:
  imports:
    - larray

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: N-dimensional labelled arrays in Python
  description: |
    LArray is an open source Python library that aims to provide tools for
    easy exploration and manipulation of N-dimensional labelled data structures.
  doc_url: https://larray.readthedocs.io/
  dev_url: https://github.com/larray-project/larray

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
