{% set version = "0.34.6" %}

package:
  name: larray
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray/archive/{{ version }}.tar.gz
  sha256: 68902ef2c83b4c982cc86d5ddfd466166ac79bfaaa1cc3691a77112e865c0833

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - numpy >=1.22
    - pandas >=0.20

test:
  imports:
    - larray

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "N-dimensional labelled arrays in Python"
  description: |
    LArray is an open source Python library that aims to provide tools for
    easy exploration and manipulation of N-dimensional labelled data structures.
  doc_url: https://larray.readthedocs.io/
  dev_url: https://github.com/larray-project/larray

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
