{% set name = "larray" %}
{% set version = "0.25.1" %}
{% set sha256 = "ef65d617563fa90038740f5e0c41b3843324a944edb6a26efed88931597ad3ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/liam2/larray/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - numpy >=1.10
    - pandas
    - pytest-runner

test:
  imports:
    - larray

about:
  home: http://github.com/liam2/larray
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: "Labeled N-dimensional array."

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
