travis:
  secure:
    BINSTAR_TOKEN: VGXWL1cIyU8LHxhKU2RmhbfldSal7aEt3D0Y7aeYTudaqmNiBqumxjTnLa4rpMR95VsrBC3mMyt6t6jinRgqn3lGNybXaaFUYJA9UbukpuNcQoEyyYEizBvr0v8ME183kujNNbiSeIS+QE6IX22YtNxC7axVwSC/Q8v1ydcIZY9QcGcq07wpjn8JpVA6vTdY5AkgrHkxs5lx19F7uXSIEXQ660x7lQ9UTio3axex4BC60O44g7euZZEwuWDGoaZQ6pTH4UFDmlkGXPVd/8ZqhUSHIkke4tKrLvXIarZsjq+PdwR0W0w0wpmjtWqfi5cR6NPGHes3e1fYrN85TQCFCk39WwJ0aEFAXuUb7CegF/IzlwbE5aNAvck0eR6COFFqQbcnjmTOQBXouVGUGbEfkvm3LyeryjDzJ6aS0bUpOqRDPsK5iUquu4GNBqcjGEmgVi1q6iaV+CIXPVLFJuawLAtJZTAMUDHSkJQNgIX4edNuDUSoye5g/RyNMPyaW+yl+XOqGrenJ7Vk58wIa1X474gZf8PKvET6LshKnX7CZ76pqfkcOoN5WjW/8TqJcDdb1J9r27qAzsvAn7rdrhzqcvoWyvrliLqyafE5y6giXRirAcGfx/M6A1tMdOKCE2THZZJoKItA3Qfh5TDUASwcjUT/lVkP6FZo2OwAWOcl7K8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
