travis:
  secure:
    BINSTAR_TOKEN: ib2Nl406Uw5K2+3R52FWp4qv0dw2ybFrImMBzwTGlJY+oGfVh7NwEO8Aj7OsJ5rpt/iS1skBXit+DB3ER8w1Yb+Bswb6WqNJaCtrIGI3SirQhmp8XLcvKGY1X8MQZ84/8LZaMSGh1johee4F98I0z6cwDIjacLnTSU5ymXxFh+g09XGaDDDKfgwGQMMIbodn+nZSt6MIVXq3GlwojsDrY0yVMS0TS+kOru2KvFOJet9iJfrE+4Ca1XUOWT6AOxrmUmXQBNy0/vwVJalJYhpCutrXt3ZiqRAQQ+LLXv93i0bi/lzkx0t7fQyOu9zPLZtQlnbOn3nO4y0UeQpWHJwsunRYpMkvmeyRqaHn2QOIXWGMO01V6mgUJyozph5rE2PWRvH9kColeOXeUCwFXhPIlu3fxvWYj3CJmPbonUteAtDlDGRiIrVzxX5wRxePHMksF9PmQOOJiV3ZtHN7ZCBDoEw2l1fnlF7YKtEKd7hqFHz2sEbeWC5f2GRZxEZSwtbwJFPq7s92NiZWYpsFNsB91bcM0F++1CWRm5GvQYkfMhxVwhox7QNF1NN0C8uGvW2S1nGYVSVNy1S6265XqmwI2Dur4L5eLwTBo/e6TqumUwX8WANs1SlO1ouhg37EXjUh9fog1aN8sGnqCUO/xu/HYvKwjH7z2pEHHELetVRuX6A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
